name: nd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  json_theme: 4.0.0+8
  dio: 4.0.6
  intl: 0.17.0
  flutter_secure_storage: 6.0.0
  flutter_chat_ui: 1.6.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/theme.json
  uses-material-design: true

